/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package i2putility.subScreens;

import i2putility.subScreens.SecondLevelDeployment;
import i2putility.components.RoundedPanel;
import java.awt.geom.RoundRectangle2D;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Alee
 */
public class Menu5 extends javax.swing.JInternalFrame {

    private final JPanel desktopPanel;
    Color DefaultColor,HoveredColor; 
    public Menu5(JPanel desktopPanel) {
        
        this.desktopPanel = desktopPanel;
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        DefaultColor=new Color(54,70,78);
        HoveredColor = new Color(240,151,70);
        secondLevel.setBackground(DefaultColor);
        advanceLevel.setBackground(DefaultColor);
        advanceLevel.setBackground(DefaultColor);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        advanceLevel = new RoundedPanel(50);
        stopTomcat2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstdeployment = new RoundedPanel(50);
        stopTomcat1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        secondLevel = new RoundedPanel(50);
        stopTomcat = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(770, 510));

        advanceLevel.setBackground(new java.awt.Color(54, 70, 78));
        advanceLevel.setPreferredSize(new java.awt.Dimension(129, 129));
        advanceLevel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                advanceLevelMouseMoved(evt);
            }
        });
        advanceLevel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                advanceLevelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                advanceLevelMouseExited(evt);
            }
        });

        stopTomcat2.setBackground(new java.awt.Color(54, 70, 78));
        stopTomcat2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        stopTomcat2.setForeground(new java.awt.Color(255, 255, 255));
        stopTomcat2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stopTomcat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/deployment/icons8-level-80.png"))); // NOI18N
        stopTomcat2.setPreferredSize(new java.awt.Dimension(129, 129));

        jLabel3.setBackground(new java.awt.Color(54, 70, 78));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Advance Level");

        javax.swing.GroupLayout advanceLevelLayout = new javax.swing.GroupLayout(advanceLevel);
        advanceLevel.setLayout(advanceLevelLayout);
        advanceLevelLayout.setHorizontalGroup(
            advanceLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advanceLevelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(advanceLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advanceLevelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(stopTomcat2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        advanceLevelLayout.setVerticalGroup(
            advanceLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advanceLevelLayout.createSequentialGroup()
                .addComponent(stopTomcat2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        firstdeployment.setBackground(new java.awt.Color(54, 70, 78));
        firstdeployment.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                firstdeploymentMouseMoved(evt);
            }
        });
        firstdeployment.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                firstdeploymentMouseWheelMoved(evt);
            }
        });
        firstdeployment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstdeploymentMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                firstdeploymentMouseExited(evt);
            }
        });

        stopTomcat1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stopTomcat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/deployment/icons8-1st-96.png"))); // NOI18N
        stopTomcat1.setPreferredSize(new java.awt.Dimension(129, 129));

        jLabel1.setBackground(new java.awt.Color(54, 70, 78));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1st Level Deployment");

        javax.swing.GroupLayout firstdeploymentLayout = new javax.swing.GroupLayout(firstdeployment);
        firstdeployment.setLayout(firstdeploymentLayout);
        firstdeploymentLayout.setHorizontalGroup(
            firstdeploymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstdeploymentLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(firstdeploymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstdeploymentLayout.createSequentialGroup()
                        .addComponent(stopTomcat1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstdeploymentLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23))))
        );
        firstdeploymentLayout.setVerticalGroup(
            firstdeploymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstdeploymentLayout.createSequentialGroup()
                .addComponent(stopTomcat1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        secondLevel.setBackground(new java.awt.Color(54, 70, 78));
        secondLevel.setPreferredSize(new java.awt.Dimension(129, 129));
        secondLevel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                secondLevelMouseMoved(evt);
            }
        });
        secondLevel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondLevelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                secondLevelMouseExited(evt);
            }
        });

        stopTomcat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stopTomcat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/deployment/icons8-second-place-ribbon-80.png"))); // NOI18N
        stopTomcat.setPreferredSize(new java.awt.Dimension(129, 129));

        jLabel2.setBackground(new java.awt.Color(54, 70, 78));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2nd Level Deployment");

        javax.swing.GroupLayout secondLevelLayout = new javax.swing.GroupLayout(secondLevel);
        secondLevel.setLayout(secondLevelLayout);
        secondLevelLayout.setHorizontalGroup(
            secondLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secondLevelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stopTomcat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secondLevelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );
        secondLevelLayout.setVerticalGroup(
            secondLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondLevelLayout.createSequentialGroup()
                .addComponent(stopTomcat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(firstdeployment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(secondLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(advanceLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(advanceLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstdeployment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(264, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void secondLevelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondLevelMouseMoved
        secondLevel.setBackground(HoveredColor);
    }//GEN-LAST:event_secondLevelMouseMoved

    private void secondLevelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondLevelMouseExited
        secondLevel.setBackground(DefaultColor);
    }//GEN-LAST:event_secondLevelMouseExited

    private void advanceLevelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advanceLevelMouseExited
        advanceLevel.setBackground(DefaultColor);
    }//GEN-LAST:event_advanceLevelMouseExited

    private void advanceLevelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advanceLevelMouseMoved
       advanceLevel.setBackground(HoveredColor);
    }//GEN-LAST:event_advanceLevelMouseMoved

    private void secondLevelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondLevelMouseClicked
        SecondLevelDeployment advanced = new SecondLevelDeployment();
        desktopPanel.removeAll();
        desktopPanel.add(advanced).setVisible(true);
    }//GEN-LAST:event_secondLevelMouseClicked

    private void advanceLevelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advanceLevelMouseClicked
        AdvanceLevelDeployment advanceLevelDeployment = new AdvanceLevelDeployment();
        desktopPanel.removeAll();
        desktopPanel.add(advanceLevelDeployment).setVisible(true);
    }//GEN-LAST:event_advanceLevelMouseClicked

    private void firstdeploymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstdeploymentMouseExited
        firstdeployment.setBackground(DefaultColor);
    }//GEN-LAST:event_firstdeploymentMouseExited

    private void firstdeploymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstdeploymentMouseClicked
        FirstLevelDeployment firstLevelDeployment = new FirstLevelDeployment();
        desktopPanel.removeAll();
        desktopPanel.add(firstLevelDeployment).setVisible(true);
    }//GEN-LAST:event_firstdeploymentMouseClicked

    private void firstdeploymentMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_firstdeploymentMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_firstdeploymentMouseWheelMoved

    private void firstdeploymentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstdeploymentMouseMoved
        firstdeployment.setBackground(HoveredColor);
    }//GEN-LAST:event_firstdeploymentMouseMoved
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel advanceLevel;
    public javax.swing.JPanel firstdeployment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel secondLevel;
    private javax.swing.JLabel stopTomcat;
    private javax.swing.JLabel stopTomcat1;
    private javax.swing.JLabel stopTomcat2;
    // End of variables declaration//GEN-END:variables
}
